baseURL = 'https://www.wwff.tech/'
title = "WWFF.tech"
copyright = "Copyright Â© 2021-2022, Mike Preston and the WWFF team."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
theme = "chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "WWFF Team"
  description = "A rag-tag bunch of random coders and hackers"
  homepageImage = "/images/pexels-aphiwat-chuangchoem-365637.jpg"
  dateFormat = "January 2, 2006"
  GitHubUser = "wwff-tech"
  SidebarRecentLimit = 5
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "mike@wwff.tech"
    twitter = "https://twitter.com/darkflib"
    linkedin = "https://linkedin.com/in/darkflib"
    github = "https://github.com/wwff-tech"
    keybase = "https://keybase.io/darkflib"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
